name: alarmclock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.2
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.2
  permission_handler: ^10.2.0
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.8
  flutter_ringtone_player: ^4.0.0+3
  intl: ^0.19.0
  flutter_time_picker_spinner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - assets/audio/holiday.mp3
  - assets/audio/peacefulwaves.mp3
  - assets/audio/gentelchimes.mp3
  - assets/audio/softpiano.mp3
  - assets/audio/morningsunshine.mp3
